defaults: &defaults
  working_directory: ~/work/terminus_plugin
  environment:
    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
  test:
    docker:
      - image: pantheonpublic/terminus-plugin-test:4.x-php8.0
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set up environment
          command: ./.circleci/set-up-globals.sh
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Install plugin
          command: terminus self:plugin:install /home/tester/work/terminus_plugin/
      - run:
          name: Test everything
          command: composer test

workflows:
  version: 2
  build_test:
    jobs:
      - test
